export const DEFAULT_EVENT_CATEGORIES = [
  'Atölye',
  'Çocuk Gelişimi',
  'Diğer',
  'Eğitim',
  'Festival',
  'Fuar',
  'Gezi',
  'Konferans',
  'Kongre',
  'Konser',
  'Parti & Canlı Müzik',
  'Sahne Sanatları',
  'Seminer',
  'Sergi',
  'Söyleşi',
  'Spor',
  'Tiyatro ve Gösteriler',
  'Webinar',
] as const;
